//! Port of packages/coding-agent/src/core/session-manager.ts entry types
//! (pi v0.84.3): the tree-structured session entry union and the
//! session-entry tree view used by branch summarization. The full
//! SessionManager (persistence, tree building) lands with its own port; the
//! entry shapes are needed earlier by compaction/branch summarization.

use std::collections::{BTreeMap, BTreeSet};

use pillar_ai::types::{Message, Usage};

use crate::core::messages::{
    BranchSummaryMessage, CodingAgentMessage, CompactionSummaryMessage, CustomContent,
    CustomMessage,
};

/// Base fields every session entry carries (upstream `SessionEntryBase`).
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SessionEntryBase {
    pub id: String,
    pub parent_id: Option<String>,
    /// Upstream stores an ISO timestamp string; the port carries the resolved
    /// millisecond timestamp.
    pub timestamp: u64,
}

/// A message entry (upstream `SessionMessageEntry`).
#[derive(Debug, Clone, PartialEq)]
pub struct SessionMessageEntry {
    pub base: SessionEntryBase,
    pub message: CodingAgentMessage,
}

/// A compaction checkpoint (upstream `CompactionEntry`).
#[derive(Debug, Clone, PartialEq)]
pub struct CompactionEntry {
    pub base: SessionEntryBase,
    pub summary: String,
    pub first_kept_entry_id: String,
    pub tokens_before: u64,
    /// Extension-specific data.
    pub details: Option<serde_json::Value>,
    /// Usage from the LLM call(s) that generated this summary.
    pub usage: Option<Usage>,
    /// True if generated by an extension (upstream `fromHook`).
    pub from_hook: bool,
}

/// A branch summary marker (upstream `BranchSummaryEntry`).
#[derive(Debug, Clone, PartialEq)]
pub struct BranchSummaryEntry {
    pub base: SessionEntryBase,
    pub from_id: String,
    pub summary: String,
    /// Extension-specific data (not sent to the LLM).
    pub details: Option<serde_json::Value>,
    /// Usage from the LLM call that generated this summary.
    pub usage: Option<Usage>,
    /// True if generated by an extension (upstream `fromHook`).
    pub from_hook: bool,
}

/// Extension state entry; does NOT participate in LLM context (upstream
/// `CustomEntry`).
#[derive(Debug, Clone, PartialEq)]
pub struct CustomEntry {
    pub base: SessionEntryBase,
    pub custom_type: String,
    pub data: Option<serde_json::Value>,
}

/// A user-defined bookmark (upstream `LabelEntry`).
#[derive(Debug, Clone, PartialEq)]
pub struct LabelEntry {
    pub base: SessionEntryBase,
    pub target_id: String,
    pub label: Option<String>,
}

/// Session metadata entry (upstream `SessionInfoEntry`).
#[derive(Debug, Clone, PartialEq)]
pub struct SessionInfoEntry {
    pub base: SessionEntryBase,
    pub name: Option<String>,
}

/// An extension-injected message that DOES participate in LLM context
/// (upstream `CustomMessageEntry`).
#[derive(Debug, Clone, PartialEq)]
pub struct CustomMessageEntry {
    pub base: SessionEntryBase,
    pub custom_type: String,
    pub content: Vec<CustomContent>,
    /// Extension-specific metadata (not sent to the LLM).
    pub details: Option<serde_json::Value>,
    /// display=false hides the entry from the TUI entirely.
    pub display: bool,
}

/// A thinking-level change marker (upstream `ThinkingLevelChangeEntry`).
#[derive(Debug, Clone, PartialEq)]
pub struct ThinkingLevelChangeEntry {
    pub base: SessionEntryBase,
    pub thinking_level: String,
}

/// A model change marker (upstream `ModelChangeEntry`).
#[derive(Debug, Clone, PartialEq)]
pub struct ModelChangeEntry {
    pub base: SessionEntryBase,
    pub provider: String,
    pub model_id: String,
}

/// The session entry union (upstream `SessionEntry`).
#[derive(Debug, Clone, PartialEq)]
pub enum SessionEntry {
    Message(SessionMessageEntry),
    ThinkingLevelChange(ThinkingLevelChangeEntry),
    ModelChange(ModelChangeEntry),
    Compaction(CompactionEntry),
    BranchSummary(BranchSummaryEntry),
    Custom(CustomEntry),
    Label(LabelEntry),
    SessionInfo(SessionInfoEntry),
    CustomMessage(CustomMessageEntry),
}

impl SessionEntry {
    pub fn id(&self) -> &str {
        match self {
            SessionEntry::Message(e) => &e.base.id,
            SessionEntry::ThinkingLevelChange(e) => &e.base.id,
            SessionEntry::ModelChange(e) => &e.base.id,
            SessionEntry::Compaction(e) => &e.base.id,
            SessionEntry::BranchSummary(e) => &e.base.id,
            SessionEntry::Custom(e) => &e.base.id,
            SessionEntry::Label(e) => &e.base.id,
            SessionEntry::SessionInfo(e) => &e.base.id,
            SessionEntry::CustomMessage(e) => &e.base.id,
        }
    }

    pub fn parent_id(&self) -> Option<&str> {
        match self {
            SessionEntry::Message(e) => e.base.parent_id.as_deref(),
            SessionEntry::ThinkingLevelChange(e) => e.base.parent_id.as_deref(),
            SessionEntry::ModelChange(e) => e.base.parent_id.as_deref(),
            SessionEntry::Compaction(e) => e.base.parent_id.as_deref(),
            SessionEntry::BranchSummary(e) => e.base.parent_id.as_deref(),
            SessionEntry::Custom(e) => e.base.parent_id.as_deref(),
            SessionEntry::Label(e) => e.base.parent_id.as_deref(),
            SessionEntry::SessionInfo(e) => e.base.parent_id.as_deref(),
            SessionEntry::CustomMessage(e) => e.base.parent_id.as_deref(),
        }
    }

    pub fn base(&self) -> &SessionEntryBase {
        match self {
            SessionEntry::Message(e) => &e.base,
            SessionEntry::ThinkingLevelChange(e) => &e.base,
            SessionEntry::ModelChange(e) => &e.base,
            SessionEntry::Compaction(e) => &e.base,
            SessionEntry::BranchSummary(e) => &e.base,
            SessionEntry::Custom(e) => &e.base,
            SessionEntry::Label(e) => &e.base,
            SessionEntry::SessionInfo(e) => &e.base,
            SessionEntry::CustomMessage(e) => &e.base,
        }
    }
}

/// Extract the coding-agent message an entry contributes to LLM context
/// (upstream `getMessageFromEntry` in branch-summarization.ts): also handles
/// compaction and branch_summary entries, unlike compaction's
/// message-only extraction.
pub fn get_message_from_entry(entry: &SessionEntry) -> Option<CodingAgentMessage> {
    match entry {
        SessionEntry::Message(message_entry) => {
            // Skip tool results - context is in the assistant's tool call.
            if matches!(
                &message_entry.message,
                CodingAgentMessage::Base(Message::ToolResult(_))
            ) {
                return None;
            }
            Some(message_entry.message.clone())
        }
        SessionEntry::CustomMessage(custom) => Some(CodingAgentMessage::Custom(CustomMessage {
            custom_type: custom.custom_type.clone(),
            content: custom.content.clone(),
            display: custom.display,
            details: custom.details.clone(),
            timestamp: custom.base.timestamp,
        })),
        SessionEntry::BranchSummary(branch) => {
            Some(CodingAgentMessage::BranchSummary(BranchSummaryMessage {
                summary: branch.summary.clone(),
                from_id: branch.from_id.clone(),
                timestamp: branch.base.timestamp,
            }))
        }
        SessionEntry::Compaction(compaction) => Some(CodingAgentMessage::CompactionSummary(
            CompactionSummaryMessage {
                summary: compaction.summary.clone(),
                tokens_before: compaction.tokens_before,
                timestamp: compaction.base.timestamp,
            },
        )),
        // These don't contribute to conversation content.
        SessionEntry::ThinkingLevelChange(_)
        | SessionEntry::ModelChange(_)
        | SessionEntry::Custom(_)
        | SessionEntry::Label(_)
        | SessionEntry::SessionInfo(_) => None,
    }
}

// ============================================================================
// Session tree view (ReadonlySessionManager subset for branch summarization)
// ============================================================================

/// A read-only session entry tree (upstream `ReadonlySessionManager`
/// narrowed to `getEntry`/`getBranch`).
#[derive(Debug, Clone, Default)]
pub struct SessionTreeView {
    entries: BTreeMap<String, SessionEntry>,
    /// Child ids by parent id; root entries use an empty parent key.
    children: BTreeMap<String, Vec<String>>,
    root_ids: Vec<String>,
}

impl SessionTreeView {
    pub fn new() -> Self {
        Self::default()
    }

    /// Insert an entry (parent must already exist for branch walks).
    pub fn insert(&mut self, entry: SessionEntry) {
        let id = entry.id().to_string();
        match entry.parent_id() {
            Some(parent) => self
                .children
                .entry(parent.to_string())
                .or_default()
                .push(id.clone()),
            None => self.root_ids.push(id.clone()),
        }
        self.entries.insert(id, entry);
    }

    pub fn get_entry(&self, id: &str) -> Option<&SessionEntry> {
        self.entries.get(id)
    }

    /// The path from root to `leaf_id`, root-first (upstream `getBranch`).
    pub fn get_branch(&self, leaf_id: &str) -> Vec<&SessionEntry> {
        let mut path: Vec<&SessionEntry> = Vec::new();
        let mut current = Some(leaf_id.to_string());
        while let Some(id) = current {
            let Some(entry) = self.entries.get(&id) else {
                break;
            };
            path.push(entry);
            current = entry.parent_id().map(str::to_string);
        }
        path.reverse();
        path
    }

    pub fn entry_ids(&self) -> BTreeSet<String> {
        self.entries.keys().cloned().collect()
    }
}
